### ISSUE TITLE
REI crashes game when trying to view Chipped recipes in 1.19.2

### ISSUE THREAD

**Issue by HappiePlant** [CookieCNetwork/Chipped#151]
I've tested this with Chipped 2.0.0, on the Fabric and Quilt Loader, and with REI 9.1.550 and 9.1.524.

I've included the Minecraft log file, REI log files and the crash report file.

- [crash-2022-10-09_15.16.24-client.txt](https://github.com/terrarium-earth/Chipped/files/9741651/crash-2022-10-09_15.16.24-client.txt) 
- [latest.log](https://github.com/terrarium-earth/Chipped/files/9741652/latest.log)
- [rei.log](https://github.com/terrarium-earth/Chipped/files/9741654/rei.log)
- [rei-issues.log](https://github.com/terrarium-earth/Chipped/files/9741655/rei-issues.log)

This snippet is from me generating a world:
```
[15:16:14] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIPlugin] stage [END], registered 6 plugins: DefaultRuntimePlugin [roughlyenoughitems], REIChippedPlugin [chipped], DefaultClientRuntimePlugin [roughlyenoughitems], FabricFluidAPISupportPlugin, DefaultPlugin [roughlyenoughitems], DefaultClientPlugin [roughlyenoughitems]
[15:16:15] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIClientPlugin] stage [END], registered 3 plugins: REIChippedPlugin [chipped], DefaultClientRuntimePlugin [roughlyenoughitems], DefaultClientPlugin [roughlyenoughitems]
[15:16:15] [REI-ReloadPlugins/ERROR]: [REI] REIChippedPlugin [chipped] plugin failed to reloadable-plugin/CategoryRegistryImpl/!
java.lang.IncompatibleClassChangeError: Class net.minecraft.class_2588 does not implement the requested interface net.minecraft.class_2561
	at me.shedaniel.rei.impl.client.registry.category.CategoryRegistryImpl.add(CategoryRegistryImpl.java:84) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.api.client.registry.category.CategoryRegistry.add(CategoryRegistry.java:80) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.api.client.registry.category.CategoryRegistry.add(CategoryRegistry.java:109) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at earth.terrarium.chipped.compat.rei.REIChippedPlugin.registerCategories(REIChippedPlugin.java:31) ~[chipped-2.0.0-fabric.jar:?]
	at me.shedaniel.rei.impl.client.registry.category.CategoryRegistryImpl.acceptPlugin(CategoryRegistryImpl.java:53) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.impl.client.registry.category.CategoryRegistryImpl.acceptPlugin(CategoryRegistryImpl.java:45) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.api.common.registry.Reloadable.acceptPlugin(Reloadable.java:72) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$9(PluginManagerImpl.java:330) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$pluginSection$4(PluginManagerImpl.java:188) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$10(PluginManagerImpl.java:320) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.pluginSection(PluginManagerImpl.java:186) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:318) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:123) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$24(RoughlyEnoughItemsCoreClient.java:462) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: java.lang.IncompatibleClassChangeError: Class net.minecraft.class_2588 does not implement the requested interface net.minecraft.class_2561
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.registry.category.CategoryRegistryImpl.lambda$endReload$0(CategoryRegistryImpl.java:66)
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.registry.category.CategoryRegistryImpl.endReload(CategoryRegistryImpl.java:67)
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.api.common.registry.Reloadable.endReload(Reloadable.java:47)
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:363)
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:123)
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$24(RoughlyEnoughItemsCoreClient.java:462)
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:16:15] [REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[15:16:15] [REI-ReloadPlugins/ERROR]: [REI] Found displays registered for unknown registry
java.lang.IllegalStateException: chipped:mechanist_workbench
	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.endReload(DisplayRegistryImpl.java:271) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.api.common.registry.Reloadable.endReload(Reloadable.java:47) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:363) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:123) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$24(RoughlyEnoughItemsCoreClient.java:462) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[15:16:15] [REI-ReloadPlugins/ERROR]: [REI] Found displays registered for unknown registry
java.lang.IllegalStateException: chipped:alchemy_bench
	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.endReload(DisplayRegistryImpl.java:271) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.api.common.registry.Reloadable.endReload(Reloadable.java:47) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:363) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:123) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$24(RoughlyEnoughItemsCoreClient.java:462) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent
[crash-2022-10-09_15.16.24-client.txt](https://github.com/terrarium-earth/Chipped/files/9741649/crash-2022-10-09_15.16.24-client.txt)
.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[15:16:15] [REI-ReloadPlugins/ERROR]: [REI] Found displays registered for unknown registry
java.lang.IllegalStateException: chipped:loom_table
	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.endReload(DisplayRegistryImpl.java:271) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.api.common.registry.Reloadable.endReload(Reloadable.java:47) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:363) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:123) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$24(RoughlyEnoughItemsCoreClient.java:462) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[15:16:15] [REI-ReloadPlugins/ERROR]: [REI] Found displays registered for unknown registry
java.lang.IllegalStateException: chipped:carpenters_table
	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.endReload(DisplayRegistryImpl.java:271) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.api.common.registry.Reloadable.endReload(Reloadable.java:47) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:363) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:123) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$24(RoughlyEnoughItemsCoreClient.java:462) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[15:16:15] [REI-ReloadPlugins/ERROR]: [REI] Found displays registered for unknown registry
java.lang.IllegalStateException: chipped:mason_table
	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.endReload(DisplayRegistryImpl.java:271) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.api.common.registry.Reloadable.endReload(Reloadable.java:47) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:363) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:123) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$24(RoughlyEnoughItemsCoreClient.java:462) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[15:16:15] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIServerPlugin] stage [END], registered 3 plugins: DefaultRuntimePlugin [roughlyenoughitems], FabricFluidAPISupportPlugin, DefaultPlugin [roughlyenoughitems]
[15:16:15] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIPlugin] with 6 plugins in 118.9 ms.
[15:16:15] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIClientPlugin] with 3 plugins in 682.2 ms.
[15:16:15] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIServerPlugin] with 3 plugins in 25.91 ms.
```

This happens when hovering over the workbench icon when viewing REI categories:
```
[15:16:24] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:890) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
Caused by: java.lang.ArrayStoreException: net.minecraft.class_2588
	at me.shedaniel.rei.impl.client.gui.widget.TabWidget.drawTooltip(TabWidget.java:138) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.impl.client.gui.widget.TabWidget.method_25394(TabWidget.java:129) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.api.client.gui.widgets.DelegateWidget.method_25394(DelegateWidget.java:48) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.impl.client.gui.widget.DelegateWidgetWithTranslate.method_25394(DelegateWidgetWithTranslate.java:58) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.method_25394(DefaultDisplayViewingScreen.java:387) ~[RoughlyEnoughItems-9.1.550.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:881) ~[client-intermediary.jar:?]
	... 16 more
```

**Comment by MCAlexisYT** [comment]
Did you mean "1.18.2" instead of "1.19.2"?

**Comment by Tors-0** [comment]
no their REI version shows they're on 1.19-1.19.2, unless they have the wrong REI version which could be the issue

**Comment by AlexNijjar** [comment]
downgrade REI
