### ISSUE TITLE
CTM Refabricated is required on servers, even if it's a client-side only mod?

### ISSUE THREAD

**Issue by pavog** [CookieCNetwork/Chipped#163]
Hi, I tried to install the mod Chipped on my fresh new Fabric 1.18.2 server.
I installed Fabric API and the mod version: [Chipped 2.0.0 [Fabric]](https://www.curseforge.com/minecraft/mc-mods/chipped/files/4020978)

Now my server tells me that I need to install the mod ctm ([CTM Refabricated](https://www.curseforge.com/minecraft/mc-mods/ctm-refabricated)):

```
[20:51:58] [main/ERROR]: Incompatible mod set!
 net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
 A potential solution has been determined:
 - Install ctm, any version.
 Unmet dependency listing:
 - Mod 'Chipped' (chipped) 2.0.0 requires any version of ctm, which is missing!
 at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.10.jar:?]
 at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.10.jar:?]
 at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.10.jar:?]
 at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.10.jar:?]
 at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.10.jar:?]
```

Why do I need to install this mod, when I want to run Chipped on a server?
The mod CTM Refabricated is a client-side only mod. See their readme on GitHub: https://github.com/CodexAdrian/ConnectedTexturesMod-Fabric

**Comment by AlexNijjar** [comment]
@CodexAdrian

**Comment by CodexAdrian** [comment]
@AlexNijjar this is on u bro, you can make it required only on client smh
