### ISSUE TITLE
[Bug]: Game isn't launching on Fabric 1.18.2

### ISSUE THREAD

**Issue by GacioSki** [CookieCNetwork/Chipped#165]
### Bug Description

I've been trying to open a game, but this error shows up, that I don't have ctm installed even though I have installed it (I've put it into mods file with chipped mod's file):
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install ctm, any version.
Unmet dependency listing:
	 - Mod 'Chipped' (chipped) 2.0.0 requires any version of ctm, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29)
	at crystallauncher.MineClient.start(MineClient.java:228)
	at crystallauncher.MineClient.main(MineClient.java:36)
https://imgur.com/a/RvBz6Ow

### Expected Behavior

The game to start

### Version

2.0.0

### Mod Loader Version

1.18.2 0.14.12

### Mod Loader

Fabric

**Comment by kwifrog** [comment]
I think you're using the Forge version of CTM, this is the one you want https://www.curseforge.com/minecraft/mc-mods/ctm-refabricated/files/3834064

**Comment by AlexNijjar** [comment]
^ yeah you need fabric ctm
