### ISSUE TITLE
[Crash Server]: Chipped carved pumpkin on a armor stand the server crashes

### ISSUE THREAD

**Issue by gamerpotion** [CookieCNetwork/Chipped#218]
### Bug Description

Im using this in my modpack - https://legacy.curseforge.com/minecraft/modpacks/darkrpg

**_Users have reported that putting a chipped carved pumpkin on armor stand crashes the entire server_**

Another user also reported:-
_**bigpugpants
 — Today at 10:37 AM
i used a work bench and it crashed the server teamet is also having that issue**_

Lastly a smaller bug but Chipped carpets are allowing users to see through them like an xray effect (screenshot at the bottom)

Looking at the crashlogs can see the following:-

`---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-07-11 03:55:58
Description: Exception in server tick loop

java.lang.AbstractMethodError: Method net/minecraft/class_2276.method_7685()Lnet/minecraft/class_1304; is abstract
	at net.minecraft.class_2276.method_7685(class_2276.java)
	at net.minecraft.class_1309.method_32326(class_1309.java:3463)
	at net.minecraft.class_1531.method_5664(class_1531.java:327)
	at net.minecraft.class_3244$1.method_33898(class_3244.java:1594)
	at net.minecraft.class_3244$1.method_33897(class_3244.java:1578)
	at net.minecraft.class_3244$1.method_34220(class_3244.java:1594)
	at net.minecraft.class_2824$class_5910.method_34213(class_2824.java:146)
	at net.minecraft.class_2824.method_34209(class_2824.java:66)
	at net.minecraft.class_3244.method_12062(class_3244.java:1571)
	at net.minecraft.class_2824.method_12251(class_2824.java:53)
	at net.minecraft.class_2824.method_11054(class_2824.java:13)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)`
	
	
<img src="https://media.discordapp.net/attachments/1118822512453750824/1128218408853438494/image.png" />

### Version

chipped-fabric-1.20.1-3.0.1.jar

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
please make separate issues with **full** crash logs

**Comment by gamerpotion** [comment]
> please make separate issues with **full** crash logs

hi, that is the only crash that appears in server's crashlogs
here is the full paste - https://pastebin.com/ph4Z5CWU

It is clear the carved pumpkin is triggering but I cant see the workbench crash so not sure but it is something the users have said on our bugs discord channel

**Comment by ThatGravyBoat** [comment]
the pumpkin is definitely not something we do, our carved pumpkins aren't equipable so another mod is assuming any carved pumpkin that is not a jack-o-lantern is which would mean that even our jack-o-lantern would also crash.

**Comment by ThatGravyBoat** [comment]
I also cant get the carpet to do that so it sounds like another mod again

**Comment by gamerpotion** [comment]
I just tested jack o lantern on armor stand on a localhost server and it crashed again https://pastebin.com/VgwczwAv

**Comment by ThatGravyBoat** [comment]
yeah so another mod is doing something and forgetting other mods can extend them

**Comment by gamerpotion** [comment]
Friends and Foes mod was causing this. Have updated them now - https://github.com/Faboslav/friends-and-foes/issues/125
@Faboslav  FYI.
