### ISSUE TITLE
[Bug]: Any type of cable staff from AE2 palced near blocks that have connected textures from chipped crashes client

### ISSUE THREAD

**Issue by Azzmurr** [CookieCNetwork/Chipped#228]
### Bug Description

Any cable staff from AE2 placed near blocks that have connected textures from chipped crashes client

### How to Reproduce?

1. Launch Minecraft
2. Go to the world
3. Place cabe from AE2 near any block from chipped that have connected textures feature

### Expected Behavior

It should not crash the client

### Version

3.0.1

### Mod Loader Version

1.20.1 - 0.14.22

### Mod Loader

Fabric

### Logs or additional context

---- Minecraft Crash Report ----
// Don't do that.

Time: 2023-08-20 16:38:20
Description: Tessellating block in world - Indigo Renderer

java.lang.ClassCastException: class earth.terrarium.athena.api.client.fabric.WrappedGetter cannot be cast to class net.fabricmc.fabric.api.rendering.data.v1.RenderAttachedBlockView (earth.terrarium.athena.api.client.fabric.WrappedGetter and net.fabricmc.fabric.api.rendering.data.v1.RenderAttachedBlockView are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @25bbe1b6)
	at appeng.block.networking.CableBusBlock.getAppearance(CableBusBlock.java:439)
	at net.fabricmc.fabric.api.block.v1.FabricBlockState.getAppearance(FabricBlockState.java:45)
	at earth.terrarium.athena.api.client.fabric.WrappedGetter.getAppearance(WrappedGetter.java:61)
	at earth.terrarium.athena.api.client.utils.CtmState.from(CtmState.java:20)
	at earth.terrarium.athena.impl.client.models.ConnectedBlockModel.getQuads(ConnectedBlockModel.java:43)
	at earth.terrarium.athena.api.client.fabric.AthenaBakedModel.emitQuads(AthenaBakedModel.java:59)
	at earth.terrarium.athena.api.client.fabric.AthenaBakedModel.emitBlockQuads(AthenaBakedModel.java:47)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:98)
	at net.minecraft.class_846$class_851$class_4578.redirect$zjh000$fabric-renderer-indigo$hookChunkBuildTessellate(class_846.java:783)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:579)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:490)
	at net.minecraft.class_846.method_22757(class_846.java:141)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at appeng.block.networking.CableBusBlock.getAppearance(CableBusBlock.java:439)
	at net.fabricmc.fabric.api.block.v1.FabricBlockState.getAppearance(FabricBlockState.java:45)
	at earth.terrarium.athena.api.client.fabric.WrappedGetter.getAppearance(WrappedGetter.java:61)
	at earth.terrarium.athena.api.client.utils.CtmState.from(CtmState.java:20)
	at earth.terrarium.athena.impl.client.models.ConnectedBlockModel.getQuads(ConnectedBlockModel.java:43)
	at earth.terrarium.athena.api.client.fabric.AthenaBakedModel.emitQuads(AthenaBakedModel.java:59)
	at earth.terrarium.athena.api.client.fabric.AthenaBakedModel.emitBlockQuads(AthenaBakedModel.java:47)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:98)
	at net.minecraft.class_846$class_851$class_4578.redirect$zjh000$fabric-renderer-indigo$hookChunkBuildTessellate(class_846.java:783)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:579)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:490)

-- Block being tessellated --
Details:
	Block: Block{chipped:white_concrete_panel}
	Block location: World: (298,68,-61), Section: (at 10,4,3 in 18,4,-4; chunk contains blocks 288,-64,-64 to 303,319,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
Stacktrace:
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:98)
	at net.minecraft.class_846$class_851$class_4578.redirect$zjh000$fabric-renderer-indigo$hookChunkBuildTessellate(class_846.java:783)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:579)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:490)
	at net.minecraft.class_846.method_22757(class_846.java:141)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Affected level --
Details:
	All players: 1 total; [class_746['Azzmurr'/85, l='ClientLevel', x=298.94, y=68.00, z=-58.21]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (288,68,-48), Section: (at 0,4,0 in 18,4,-3; chunk contains blocks 288,-64,-48 to 303,319,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 1055 game time, 1055 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_43589(class_310.java:895)
	at net.minecraft.class_310.method_1514(class_310.java:791)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.6, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 721248720 bytes (687 MiB) / 2298478592 bytes (2192 MiB) up to 12582912000 bytes (12000 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5900X 12-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 3080 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2208
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3667
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 3.60
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384.00
	Memory slot #3 clockSpeed (GHz): 3.60
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 93605.92
	Virtual memory used (MB): 49403.49
	Swap memory total (MB): 28160.00
	Swap memory used (MB): 230.48
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12000M
	Fabric Mods: 
		ae2: Applied Energistics 2 15.0.7-beta
			team_reborn_energy: Energy 3.0.0
		athena: Athena 3.0.1
		chipped: Chipped 3.0.1
		fabric-api: Fabric API 0.87.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.2+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.2+6bdb2ed077
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.2+6bdb2ed077
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.14.22
		java: Java HotSpot(TM) 64-Bit Server VM 17
		minecraft: Minecraft 1.20.1
		resourcefullib: Resourceful Lib 2.1.9
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.67, NVIDIA Corporation
	Window size: 3840x1529
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	CPU: 24x AMD Ryzen 9 5900X 12-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['Azzmurr'/85, l='ServerLevel[New World]', x=298.94, y=68.00, z=-58.21]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Comment by ThatGravyBoat** [comment]
This is an Athena issue please report on the Athena Github https://github.com/terrarium-earth/Athena/issues
